# Copyright (c) 2025 Bart van de Lint, Uwe Fechner
# SPDX-License-Identifier: MPL-2.0

"""
Factory functions for building SystemStructure objects for the ram-air kite models.

These functions were previously part of SymbolicAWEModels.jl but were moved here
when the ram-air kite models were extracted to this package.
"""

# Internal helpers from SymbolicAWEModels that are not exported
using SymbolicAWEModels: create_vsm_wing

# ==================== TETHER CREATION HELPERS ==================== #

"""
    find_axis_point(P, l, v=[0,0,1])

Calculate the coordinates of a point `Q` that lies on a line defined by vector `v`
and is at a distance `l` from a given point `P`.
"""
function find_axis_point(P, l, v=[0,0,1])
    l = float(l)
    D = (v ⋅ P)^2 - norm(v)^2 * (norm(P)^2 - l^2)
    D < 0 && error("No real solution: l is too small or parameters invalid")
    t = (v ⋅ P - √D) / norm(v)^2
    return [t * v[1], t * v[2], t * v[3]]
end

"""
    add_tether!(points, tethers, name, set, attach_point; z, d_pos,
                diameter_mm, unit_stiffness, unit_damping)

Append a ground anchor `Point` and a `Tether` connecting `attach_point` on the
kite to it. The intermediate points and segments are auto-generated by
`SystemStructure`, which also scales the placement to `set.l_tether`.

Returns the updated `points` and `tethers` vectors and the anchor point name
(used as the winch point and, for the last tether, the transform base point).
"""
function add_tether!(points, tethers, name, set::Settings, attach_point;
                     z=[0,0,1], d_pos=zeros(3), diameter_mm=NaN,
                     unit_stiffness=NaN, unit_damping=NaN)
    anchor_pos = find_axis_point(attach_point.pos_cad, set.l_tether, z) .+ d_pos
    anchor_name = Symbol(name, :_anchor)
    points = [points; Point(anchor_name, anchor_pos, STATIC; transform=1)]
    diameter = isnan(diameter_mm) ? NaN : diameter_mm * 0.001
    tethers = [tethers; Tether(name, set.l_tether;
                               start_point=attach_point.name, end_point=anchor_name,
                               n_segments=set.segments, diameter,
                               unit_stiffness, unit_damping)]
    return points, tethers, anchor_name
end

"""
    bridle_kwargs(set) -> NamedTuple

Return keyword arguments for creating bridle `Segment` objects.

Bridle lines use `set.bridle_tether_diameter` with a stiffness factor of 0.01
relative to the standard tether stiffness, modelling their flexibility.
"""
function bridle_kwargs(set::Settings)
    diameter_m = 0.001 * set.bridle_tether_diameter
    unit_stiffness = set.e_tether * (diameter_m / 2)^2 * π * 0.01
    return (diameter_mm=set.bridle_tether_diameter, unit_stiffness=unit_stiffness)
end

# ==================== MODEL FACTORY FUNCTIONS ==================== #

"""
    wing_surface_pos(vsm_wing, span_frac, chord_frac)

Position in the CAD frame at `span_frac` along the span and `chord_frac` along the chord
of `vsm_wing`, interpolated linearly between its unrefined sections. `span_frac` runs
from -1 at the +y tip to 1 at the -y tip and measures leading-edge distance in the y-z
plane, so the sweep does not shift it.
"""
function wing_surface_pos(vsm_wing, span_frac, chord_frac)
    sections = sort(vsm_wing.unrefined_sections; by=section -> -section.LE_point[2])
    span_dist = cumsum([0.0; [norm(sections[i+1].LE_point[2:3] - sections[i].LE_point[2:3])
                              for i in 1:length(sections)-1]])
    section_fracs = 2 .* span_dist ./ span_dist[end] .- 1
    i = clamp(searchsortedlast(section_fracs, span_frac), 1, length(sections) - 1)
    weight = (span_frac - section_fracs[i]) / (section_fracs[i+1] - section_fracs[i])
    le_pos = (1 - weight) * sections[i].LE_point + weight * sections[i+1].LE_point
    te_pos = (1 - weight) * sections[i].TE_point + weight * sections[i+1].TE_point
    return le_pos + chord_frac * (te_pos - le_pos)
end

"""
    create_ram_sys_struct(set::Settings; d_winch_pos, prn)

Create a `SystemStructure` for the primary "ram" model with a stability-enhancing bridle.

The model features 4 deformable stations (4 deforming points each),
a complex pulley bridle system, 4 main tethers, and 3 winches.

# Arguments
- `set::Settings`: Configuration parameters from `KiteUtils.jl`.

# Keywords
- `d_winch_pos`: Winch position offsets. Default `[zeros(3), zeros(3)]`.
- `prn=true`: If true, print info messages about auto-generated components.
"""
function create_ram_sys_struct(set::Settings; d_winch_pos=[zeros(3), zeros(3)], prn=true)
    vsm_set_path = joinpath(get_data_path(), "vsm_settings.yaml")
    vsm_set = VortexStepMethod.VSMSettings(vsm_set_path; data_prefix=false)
    vsm_wing = create_vsm_wing(set, vsm_set; prn=false)
    points = Point[]
    stations = Station[]
    segments = Segment[]
    pulleys = Pulley[]
    tethers = Tether[]

    attach_points = Point[]

    bridle_top_left = set.top_bridle_points
    bridle_top_right = [point .* [1, -1, 1] for point in bridle_top_left]

    z = vsm_wing.R_cad_body[:, 3]

    function create_bridle(bridle_top, span_fracs, points, stations, segments, pulleys, attach_points)
        i_pnt = length(points)
        i_seg = length(segments)
        i_pul = length(pulleys)
        i_station = length(stations)

        points_new = [
            Point(1+i_pnt, wing_surface_pos(vsm_wing, span_fracs[1], set.bridle_fracs[1]),
                  BODY_STATIC; wing=1)
            Point(2+i_pnt, wing_surface_pos(vsm_wing, span_fracs[1], set.bridle_fracs[2]),
                  BODY_STATIC; wing=1)
            Point(3+i_pnt, wing_surface_pos(vsm_wing, span_fracs[1], set.bridle_fracs[3]),
                  BODY_STATIC; wing=1)
            Point(4+i_pnt, wing_surface_pos(vsm_wing, span_fracs[1], set.bridle_fracs[4]),
                  BODY_STATIC; wing=1)
            Point(5+i_pnt, wing_surface_pos(vsm_wing, span_fracs[2], set.bridle_fracs[1]),
                  BODY_STATIC; wing=1)
            Point(6+i_pnt, wing_surface_pos(vsm_wing, span_fracs[2], set.bridle_fracs[2]),
                  BODY_STATIC; wing=1)
            Point(7+i_pnt, wing_surface_pos(vsm_wing, span_fracs[2], set.bridle_fracs[3]),
                  BODY_STATIC; wing=1)
            Point(8+i_pnt, wing_surface_pos(vsm_wing, span_fracs[2], set.bridle_fracs[4]),
                  BODY_STATIC; wing=1)
        ]
        stations_new = [
            Station(1+i_station, [1+i_pnt, 2+i_pnt, 3+i_pnt, 4+i_pnt], DYNAMIC, 0.25)
            Station(2+i_station, [5+i_pnt, 6+i_pnt, 7+i_pnt, 8+i_pnt], DYNAMIC, 0.25)
        ]

        body_frame_damping = 1.0
        points_new = [
            points_new
            Point(9+i_pnt, bridle_top[1], DYNAMIC; body_frame_damping, world_frame_damping=0.0, transform=1, wing=1)
            Point(10+i_pnt, bridle_top[2], DYNAMIC; body_frame_damping, world_frame_damping=0.0, transform=1, wing=1)
            Point(11+i_pnt, bridle_top[3], DYNAMIC; body_frame_damping, world_frame_damping=0.0, transform=1, wing=1)
            Point(12+i_pnt, bridle_top[4], DYNAMIC; body_frame_damping, world_frame_damping=0.0, transform=1, wing=1)
            Point(13+i_pnt, bridle_top[2] - 1z, DYNAMIC; body_frame_damping, world_frame_damping=0.0, transform=1, wing=1)
            Point(14+i_pnt, bridle_top[1] - 2z, DYNAMIC; body_frame_damping, world_frame_damping=0.0, transform=1, wing=1)
            Point(15+i_pnt, bridle_top[3] - 2z, DYNAMIC; body_frame_damping, world_frame_damping=0.0, transform=1, wing=1)
            Point(16+i_pnt, bridle_top[1] - 4z, DYNAMIC; body_frame_damping, world_frame_damping=0.0, transform=1, wing=1)
            Point(17+i_pnt, bridle_top[3] - 4z, DYNAMIC; body_frame_damping, world_frame_damping=0.0, transform=1, wing=1)
        ]
        bk = bridle_kwargs(set)
        segments_new = [
            Segment(1+i_seg, set, 1+i_pnt, 9+i_pnt; bk...)
            Segment(2+i_seg, set, 2+i_pnt, 10+i_pnt; bk...)
            Segment(3+i_seg, set, 3+i_pnt, 11+i_pnt; bk...)
            Segment(4+i_seg, set, 4+i_pnt, 12+i_pnt; bk...)

            Segment(5+i_seg, set, 5+i_pnt, 9+i_pnt; bk...)
            Segment(6+i_seg, set, 6+i_pnt, 10+i_pnt; bk...)
            Segment(7+i_seg, set, 7+i_pnt, 11+i_pnt; bk...)
            Segment(8+i_seg, set, 8+i_pnt, 12+i_pnt; bk...)

            Segment(9+i_seg, set, 9+i_pnt, 14+i_pnt; bk..., l0=2)
            Segment(10+i_seg, set, 10+i_pnt, 13+i_pnt; bk..., l0=1)
            Segment(11+i_seg, set, 11+i_pnt, 15+i_pnt; bk..., l0=2)
            Segment(12+i_seg, set, 12+i_pnt, 17+i_pnt; bk..., l0=4)
            Segment(13+i_seg, set, 13+i_pnt, 14+i_pnt; bk..., l0=1)
            Segment(14+i_seg, set, 13+i_pnt, 15+i_pnt; bk..., l0=1)
            Segment(15+i_seg, set, 14+i_pnt, 16+i_pnt; bk..., l0=2)
            Segment(16+i_seg, set, 15+i_pnt, 16+i_pnt; bk..., l0=2)
            Segment(17+i_seg, set, 15+i_pnt, 17+i_pnt; bk..., l0=2)
        ]
        pulleys_new = [
            Pulley(1+i_pul, 13+i_seg, 14+i_seg, DYNAMIC)
            Pulley(2+i_pul, 16+i_seg, 17+i_seg, DYNAMIC)
        ]
        append!(points, points_new)
        append!(stations, stations_new)
        append!(segments, segments_new)
        append!(pulleys, pulleys_new)
        push!(attach_points, points[end-1])
        push!(attach_points, points[end])
        return nothing
    end

    span_fracs = [-3/4, -1/4, 1/4, 3/4]
    create_bridle(bridle_top_left, span_fracs[[1, 2]], points, stations, segments, pulleys, attach_points)
    create_bridle(bridle_top_right, span_fracs[[3, 4]], points, stations, segments, pulleys, attach_points)

    points, tethers, power_left_anchor =
        add_tether!(points, tethers, :power_left, set, attach_points[1];
                    z, diameter_mm=set.power_tether_diameter)
    points, tethers, _ =
        add_tether!(points, tethers, :power_right, set, attach_points[3];
                    z, diameter_mm=set.power_tether_diameter)
    points, tethers, steering_left_anchor =
        add_tether!(points, tethers, :steering_left, set, attach_points[2];
                    z, d_pos=d_winch_pos[1], diameter_mm=set.steering_tether_diameter)
    points, tethers, steering_right_anchor =
        add_tether!(points, tethers, :steering_right, set, attach_points[4];
                    z, d_pos=d_winch_pos[2], diameter_mm=set.steering_tether_diameter)

    winches = [
        Winch(:power_winch, set, [:power_left, :power_right]; winch_point=power_left_anchor)
        Winch(:steering_left_winch, set, [:steering_left]; winch_point=steering_left_anchor)
        Winch(:steering_right_winch, set, [:steering_right]; winch_point=steering_right_anchor)
    ]

    vsm_aero = BodyAerodynamics([vsm_wing])
    vsm_solver = Solver(vsm_aero; solver_type=NONLIN, atol=2e-8, rtol=2e-8)
    wings = [VSMWing(1, vsm_aero, vsm_wing, vsm_solver, [1, 2, 3, 4], I(3), zeros(3))]
    transforms = [Transform(1, deg2rad(float(set.elevation)), deg2rad(float(set.azimuth)), deg2rad(float(set.heading));
                             base_pos=zeros(3), base_point=steering_right_anchor, wing=1)]

    return SystemStructure("ram", set; points, stations, segments, pulleys, tethers, winches, wings, transforms, prn)
end

"""
    create_4_attach_ram_sys_struct(set::Settings; prn)

Create a `SystemStructure` for a ram-air kite with a 4-point attachment bridle.

Similar to `create_ram_sys_struct` but with all four bridle attachment points
deforming with the wing group twist dynamics.

# Arguments
- `set::Settings`: Configuration parameters from `KiteUtils.jl`.

# Keywords
- `prn=true`: If true, print info messages about auto-generated components.
"""
function create_4_attach_ram_sys_struct(set::Settings; prn=true)
    vsm_set_path = joinpath(get_data_path(), "vsm_settings.yaml")
    vsm_set = VortexStepMethod.VSMSettings(vsm_set_path; data_prefix=false)
    vsm_wing = create_vsm_wing(set, vsm_set; prn=false)
    points = Point[]
    stations = Station[]
    segments = Segment[]
    pulleys = Pulley[]
    tethers = Tether[]

    attach_points = Point[]

    bridle_top_left = set.top_bridle_points
    bridle_top_right = [point .* [1, -1, 1] for point in bridle_top_left]

    z = vsm_wing.R_cad_body[:, 3]

    function create_bridle(bridle_top, span_fracs, points, stations, segments, pulleys, attach_points)
        i_pnt = length(points)
        i_seg = length(segments)
        i_pul = length(pulleys)
        i_station = length(stations)

        points_new = [
            Point(1+i_pnt, wing_surface_pos(vsm_wing, span_fracs[1], set.bridle_fracs[1]),
                  BODY_STATIC; wing=1)
            Point(2+i_pnt, wing_surface_pos(vsm_wing, span_fracs[1], set.bridle_fracs[2]),
                  BODY_STATIC; wing=1)
            Point(3+i_pnt, wing_surface_pos(vsm_wing, span_fracs[1], set.bridle_fracs[3]),
                  BODY_STATIC; wing=1)
            Point(4+i_pnt, wing_surface_pos(vsm_wing, span_fracs[1], set.bridle_fracs[4]),
                  BODY_STATIC; wing=1)
            Point(5+i_pnt, wing_surface_pos(vsm_wing, span_fracs[2], set.bridle_fracs[1]),
                  BODY_STATIC; wing=1)
            Point(6+i_pnt, wing_surface_pos(vsm_wing, span_fracs[2], set.bridle_fracs[2]),
                  BODY_STATIC; wing=1)
            Point(7+i_pnt, wing_surface_pos(vsm_wing, span_fracs[2], set.bridle_fracs[3]),
                  BODY_STATIC; wing=1)
            Point(8+i_pnt, wing_surface_pos(vsm_wing, span_fracs[2], set.bridle_fracs[4]),
                  BODY_STATIC; wing=1)
        ]
        stations_new = [
            Station(1+i_station, [1+i_pnt, 2+i_pnt, 3+i_pnt, 4+i_pnt], DYNAMIC, set.bridle_fracs[2])
            Station(2+i_station, [5+i_pnt, 6+i_pnt, 7+i_pnt, 8+i_pnt], DYNAMIC, set.bridle_fracs[2])
        ]

        body_frame_damping = 1.0
        points_new = [
            points_new
            Point(9+i_pnt, bridle_top[1], DYNAMIC; body_frame_damping, world_frame_damping=0.0, transform=1, wing=1)
            Point(10+i_pnt, bridle_top[2], DYNAMIC; body_frame_damping, world_frame_damping=0.0, transform=1, wing=1)
            Point(11+i_pnt, bridle_top[3], DYNAMIC; body_frame_damping, world_frame_damping=0.0, transform=1, wing=1)
            Point(12+i_pnt, bridle_top[4], DYNAMIC; body_frame_damping, world_frame_damping=0.0, transform=1, wing=1)
            Point(13+i_pnt, bridle_top[2] - 1z, DYNAMIC; body_frame_damping, world_frame_damping=0.0, transform=1, wing=1)
            Point(14+i_pnt, bridle_top[1] - 2z, DYNAMIC; body_frame_damping, world_frame_damping=0.0, transform=1, wing=1)
            Point(15+i_pnt, bridle_top[3] - 2z, DYNAMIC; body_frame_damping, world_frame_damping=0.0, transform=1, wing=1)
            Point(16+i_pnt, bridle_top[1] - 4z, DYNAMIC; body_frame_damping, world_frame_damping=0.0, transform=1, wing=1)
            Point(17+i_pnt, bridle_top[3] - 4z, DYNAMIC; body_frame_damping, world_frame_damping=0.0, transform=1, wing=1)
        ]
        bk = bridle_kwargs(set)
        segments_new = [
            Segment(1+i_seg, set, 1+i_pnt, 9+i_pnt; bk...)
            Segment(2+i_seg, set, 2+i_pnt, 10+i_pnt; bk...)
            Segment(3+i_seg, set, 3+i_pnt, 11+i_pnt; bk...)
            Segment(4+i_seg, set, 4+i_pnt, 12+i_pnt; bk...)
            Segment(5+i_seg, set, 5+i_pnt, 9+i_pnt; bk...)
            Segment(6+i_seg, set, 6+i_pnt, 10+i_pnt; bk...)
            Segment(7+i_seg, set, 7+i_pnt, 11+i_pnt; bk...)
            Segment(8+i_seg, set, 8+i_pnt, 12+i_pnt; bk...)
            Segment(9+i_seg, set, 9+i_pnt, 14+i_pnt; bk..., l0=2)
            Segment(10+i_seg, set, 10+i_pnt, 13+i_pnt; bk..., l0=1)
            Segment(11+i_seg, set, 11+i_pnt, 15+i_pnt; bk..., l0=2)
            Segment(12+i_seg, set, 12+i_pnt, 17+i_pnt; bk..., l0=4)
            Segment(13+i_seg, set, 13+i_pnt, 14+i_pnt; bk..., l0=1)
            Segment(14+i_seg, set, 13+i_pnt, 15+i_pnt; bk..., l0=1)
            Segment(15+i_seg, set, 14+i_pnt, 16+i_pnt; bk..., l0=2)
            Segment(16+i_seg, set, 15+i_pnt, 16+i_pnt; bk..., l0=2)
            Segment(17+i_seg, set, 15+i_pnt, 17+i_pnt; bk..., l0=2)
        ]
        pulleys_new = [
            Pulley(1+i_pul, 13+i_seg, 14+i_seg, DYNAMIC)
            Pulley(2+i_pul, 16+i_seg, 17+i_seg, DYNAMIC)
        ]
        append!(points, points_new)
        append!(stations, stations_new)
        append!(segments, segments_new)
        append!(pulleys, pulleys_new)
        push!(attach_points, points[end-1])
        push!(attach_points, points[end])
        return nothing
    end

    span_fracs = [-3/4, -1/4, 1/4, 3/4]
    create_bridle(bridle_top_left, span_fracs[[1, 2]], points, stations, segments, pulleys, attach_points)
    create_bridle(bridle_top_right, span_fracs[[3, 4]], points, stations, segments, pulleys, attach_points)

    points, tethers, power_left_anchor =
        add_tether!(points, tethers, :power_left, set, attach_points[1];
                    z, diameter_mm=set.power_tether_diameter)
    points, tethers, _ =
        add_tether!(points, tethers, :power_right, set, attach_points[3];
                    z, diameter_mm=set.power_tether_diameter)
    points, tethers, steering_left_anchor =
        add_tether!(points, tethers, :steering_left, set, attach_points[2];
                    z, diameter_mm=set.steering_tether_diameter)
    points, tethers, steering_right_anchor =
        add_tether!(points, tethers, :steering_right, set, attach_points[4];
                    z, diameter_mm=set.steering_tether_diameter)

    winches = [
        Winch(:power_winch, set, [:power_left, :power_right]; winch_point=power_left_anchor)
        Winch(:steering_left_winch, set, [:steering_left]; winch_point=steering_left_anchor)
        Winch(:steering_right_winch, set, [:steering_right]; winch_point=steering_right_anchor)
    ]

    vsm_aero = BodyAerodynamics([vsm_wing])
    vsm_solver = Solver(vsm_aero; solver_type=NONLIN, atol=2e-8, rtol=2e-8)
    wings = [VSMWing(1, vsm_aero, vsm_wing, vsm_solver, [1, 2, 3, 4], I(3), zeros(3))]
    transforms = [Transform(1, deg2rad(float(set.elevation)), deg2rad(float(set.azimuth)), deg2rad(float(set.heading));
                             base_pos=zeros(3), base_point=steering_right_anchor, wing=1)]

    return SystemStructure("4_attach_ram", set; points, stations, segments, pulleys, tethers, winches, wings, transforms, prn)
end

"""
    create_simple_ram_sys_struct(set::Settings; unit_stiffness, unit_damping, prn)

Create a simplified `SystemStructure` for a ram-air kite with direct tether connections.

Simplified bridle without pulley system. Each tether is a single segment.

# Arguments
- `set::Settings`: Configuration parameters.

# Keywords
- `unit_stiffness`: Per-tether unit stiffness values. Default `fill(NaN, 4)`.
- `unit_damping`: Per-tether unit damping values. Default `fill(NaN, 4)`.
- `prn=true`: If true, print info messages about auto-generated components.
"""
function create_simple_ram_sys_struct(set::Settings;
                                      unit_stiffness=fill(NaN, 4),
                                      unit_damping=fill(NaN, 4),
                                      prn=true)
    set.segments = 1
    vsm_set_path = joinpath(get_data_path(), "vsm_settings.yaml")
    vsm_set = VortexStepMethod.VSMSettings(vsm_set_path; data_prefix=false)
    vsm_wing = create_vsm_wing(set, vsm_set; prn=false)
    span_fracs = [-1/2, 1/2]

    bridle_top_left = set.top_bridle_points
    bridle_top_right = [point .* [1, -1, 1] for point in bridle_top_left]

    points = [
        Point(1, bridle_top_left[2], BODY_STATIC; wing=1)
        Point(2, bridle_top_right[2], BODY_STATIC; wing=1)
        Point(3, wing_surface_pos(vsm_wing, span_fracs[1], set.bridle_fracs[4]), BODY_STATIC; wing=1)
        Point(4, wing_surface_pos(vsm_wing, span_fracs[2], set.bridle_fracs[4]), BODY_STATIC; wing=1)
        Point(5, [0, 0, -float(set.l_tether)], STATIC; transform=1)
        Point(6, [0, 0, -float(set.l_tether)], STATIC; transform=1)
        Point(7, [0, 0, -float(set.l_tether)], STATIC; transform=1)
        Point(8, [0, 0, -float(set.l_tether)], STATIC; transform=1)
        Point(9, wing_surface_pos(vsm_wing, span_fracs[1], set.bridle_fracs[1]), BODY_STATIC; wing=1)
        Point(10, wing_surface_pos(vsm_wing, span_fracs[2], set.bridle_fracs[1]), BODY_STATIC; wing=1)
    ]
    stations = [
        Station(1, [9, 3], DYNAMIC, 0.25)
        Station(2, [10, 4], DYNAMIC, 0.25)
    ]
    segments = [
        Segment(1, set, 1, 5; unit_stiffness=unit_stiffness[1], unit_damping=unit_damping[1], diameter_mm=set.power_tether_diameter)
        Segment(2, set, 2, 6; unit_stiffness=unit_stiffness[2], unit_damping=unit_damping[2], diameter_mm=set.power_tether_diameter)
        Segment(3, set, 3, 7; unit_stiffness=unit_stiffness[3], unit_damping=unit_damping[3], diameter_mm=set.steering_tether_diameter)
        Segment(4, set, 4, 8; unit_stiffness=unit_stiffness[4], unit_damping=unit_damping[4], diameter_mm=set.steering_tether_diameter)
    ]
    tethers = [
        Tether(1, [1], set.l_tether)
        Tether(2, [2], set.l_tether)
        Tether(3, [3], set.l_tether)
        Tether(4, [4], set.l_tether)
    ]
    winches = [
        Winch(1, set, [1, 2]; winch_point=5)
        Winch(2, set, [3]; winch_point=7)
        Winch(3, set, [4]; winch_point=8)
    ]
    vsm_aero = BodyAerodynamics([vsm_wing])
    vsm_solver = Solver(vsm_aero; solver_type=NONLIN, atol=2e-8, rtol=2e-8)
    wings = [VSMWing(1, vsm_aero, vsm_wing, vsm_solver, [1, 2], I(3), zeros(3))]
    transforms = [
        Transform(1, deg2rad(float(set.elevation)), deg2rad(float(set.azimuth)), deg2rad(float(set.heading));
                  base_pos=zeros(3), base_point=5, wing=1)
    ]

    return SystemStructure("simple_ram", set;
        points, stations, segments, tethers, winches, wings, transforms, prn)
end

"""
    create_tether_sys_struct(set::Settings; unit_stiffness, unit_damping, prn)

Create a simplified `SystemStructure` for testing tether dynamics only.

4 independent tethers, each a dynamic point connected to a fixed anchor.
No wing or bridle system.

# Arguments
- `set::Settings`: Configuration parameters.

# Keywords
- `unit_stiffness`: Per-tether unit stiffness values. Default `fill(NaN, 4)`.
- `unit_damping`: Per-tether unit damping values. Default `fill(NaN, 4)`.
- `prn=true`: If true, print info messages about auto-generated components.
"""
function create_tether_sys_struct(set::Settings;
                                  unit_stiffness=fill(NaN, 4),
                                  unit_damping=fill(NaN, 4),
                                  prn=true)
    points = [
        Point(:power_left, zeros(3), DYNAMIC; fix_sphere=true, transform=1)
        Point(:power_right, zeros(3), DYNAMIC; fix_sphere=true, transform=1)
        Point(:steering_left, zeros(3), DYNAMIC; fix_sphere=true, transform=1)
        Point(:steering_right, zeros(3), DYNAMIC; fix_sphere=true, transform=1)
    ]
    tethers = Tether[]

    points, tethers, power_left_anchor =
        add_tether!(points, tethers, :power_left, set, points[1];
                    unit_stiffness=unit_stiffness[1], unit_damping=unit_damping[1],
                    diameter_mm=set.power_tether_diameter)
    points, tethers, _ =
        add_tether!(points, tethers, :power_right, set, points[2];
                    unit_stiffness=unit_stiffness[2], unit_damping=unit_damping[2],
                    diameter_mm=set.power_tether_diameter)
    points, tethers, steering_left_anchor =
        add_tether!(points, tethers, :steering_left, set, points[3];
                    unit_stiffness=unit_stiffness[3], unit_damping=unit_damping[3],
                    diameter_mm=set.steering_tether_diameter)
    points, tethers, steering_right_anchor =
        add_tether!(points, tethers, :steering_right, set, points[4];
                    unit_stiffness=unit_stiffness[4], unit_damping=unit_damping[4],
                    diameter_mm=set.steering_tether_diameter)

    winches = [
        Winch(:power_winch, set, [:power_left, :power_right]; brake=true, winch_point=power_left_anchor)
        Winch(:steering_left_winch, set, [:steering_left]; brake=true, winch_point=steering_left_anchor)
        Winch(:steering_right_winch, set, [:steering_right]; brake=true, winch_point=steering_right_anchor)
    ]
    transforms = [Transform(1, deg2rad(float(set.elevation)), deg2rad(float(set.azimuth)), deg2rad(float(set.heading));
                             base_pos=zeros(3), base_point=steering_right_anchor, rot_point=:power_left)]

    return SystemStructure("tether", set; points, tethers, winches, transforms, prn)
end

"""
    create_sys_struct(set::Settings; kwargs...)

Dispatcher that calls the appropriate factory function based on `set.physical_model`.

# Arguments
- `set::Settings`: Configuration parameters from `KiteUtils.jl`.

# Keywords
- `prn=true`: If true, print info messages about auto-generated components.
- Additional keyword arguments are forwarded to the underlying factory function.
"""
function create_sys_struct(set::Settings; kwargs...)
    model = set.physical_model
    if model == "ram"
        return create_ram_sys_struct(set; kwargs...)
    elseif model == "simple_ram"
        return create_simple_ram_sys_struct(set; kwargs...)
    elseif model == "4_attach_ram"
        return create_4_attach_ram_sys_struct(set; kwargs...)
    elseif model == "tether"
        return create_tether_sys_struct(set; kwargs...)
    else
        error("Unknown physical_model: \"$model\". Supported: \"ram\", \"simple_ram\", \"4_attach_ram\", \"tether\"")
    end
end
